baseURL = "https://city2011.github.io/"  # 暂时先这样写，后面会改
languageCode = "zh-cn"
title = "我的个人博客"
theme = "papermod"  # 指定使用的主题

# 更多主题特定配置请参考主题文档
[params]
  description = "这是我的个人博客测试"

[menu]
  # 可以在这里配置导航菜单
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
